# Generated by ChatGPT, with additional changes/adjustments
# 2026-04-06

from pyspark.sql import SparkSession
from pyspark.sql.functions import (
    col,
    lit,
    when,
    to_timestamp,
    to_date,
    countDistinct,
    sum as spark_sum,
    avg,
    max as spark_max,
    datediff,
    coalesce,
    min as spark_min,
    max as spark_max_fn,
)
from pyspark.ml.feature import VectorAssembler
from functools import reduce
from datetime import datetime, timedelta


# --------------------------------------------------
# 1. Create Spark session
# --------------------------------------------------
spark = (
    SparkSession.builder
    .appName("AutoCutoffFeaturePipeline")
    .getOrCreate()
)


# --------------------------------------------------
# 2. Read and clean events
# --------------------------------------------------
events = (
    spark.read
    .option("header", True)
    .json("../events.jsonl")
)

events = (
    events
    .withColumn("timestamp", to_timestamp(col("timestamp")))
    .withColumn("price", col("price").cast("double"))
    .dropna(subset=["event_id", "user_id", "event_type", "timestamp"])
    .dropDuplicates(["event_id"])
    .withColumn("price", coalesce(col("price"), lit(0.0)))
    .withColumn("event_date", to_date(col("timestamp")))
)


# --------------------------------------------------
# 3. Automatically generate valid cutoff dates
# --------------------------------------------------
date_bounds = events.agg(
    spark_min("event_date").alias("min_date"),
    spark_max_fn("event_date").alias("max_date")
).collect()[0]

min_date = date_bounds["min_date"]
max_date = date_bounds["max_date"]

short_window_days = 7
long_window_days = 30
label_days = 7

first_cutoff = min_date + timedelta(days=long_window_days)
last_cutoff = max_date - timedelta(days=label_days)

cutoff_dates = []
current_date = first_cutoff
while current_date <= last_cutoff:
    cutoff_dates.append(current_date.strftime("%Y-%m-%d"))
    current_date += timedelta(days=1)

print("Min event date:", min_date)
print("Max event date:", max_date)
print("First valid cutoff:", first_cutoff)
print("Last valid cutoff:", last_cutoff)
print("Number of cutoffs:", len(cutoff_dates))


# --------------------------------------------------
# 4. Helper function to add event indicator columns
# --------------------------------------------------
def add_event_flags(df):
    return (
        df
        .withColumn("is_view", when(col("event_type") == "view", 1).otherwise(0))
        .withColumn("is_click", when(col("event_type") == "click", 1).otherwise(0))
        .withColumn("is_cart", when(col("event_type") == "add_to_cart", 1).otherwise(0))
        .withColumn("is_purchase", when(col("event_type") == "purchase", 1).otherwise(0))
    )


# --------------------------------------------------
# 5. Helper function to aggregate features
# --------------------------------------------------
def aggregate_features(df, suffix):
    return (
        df.groupBy("user_id")
        .agg(
            spark_sum("is_view").alias(f"views_{suffix}"),
            spark_sum("is_click").alias(f"clicks_{suffix}"),
            spark_sum("is_cart").alias(f"carts_{suffix}"),
            spark_sum("is_purchase").alias(f"purchases_{suffix}"),
            spark_sum("price").alias(f"spend_{suffix}"),
            avg(when(col("event_type") == "purchase", col("price"))).alias(f"avg_order_value_{suffix}"),
            countDistinct("product_id").alias(f"distinct_products_{suffix}"),
            countDistinct(col("timestamp").cast("date")).alias(f"active_days_{suffix}"),
            spark_max("timestamp").alias(f"last_event_ts_{suffix}")
        )
    )


# --------------------------------------------------
# 6. Build one snapshot for one cutoff date
# --------------------------------------------------
def build_training_snapshot(
    events_df,
    cutoff_date_str,
    short_window_days=7,
    long_window_days=30,
    label_days=7
):
    cutoff_dt = datetime.strptime(cutoff_date_str, "%Y-%m-%d")

    short_start_dt = cutoff_dt - timedelta(days=short_window_days)
    long_start_dt = cutoff_dt - timedelta(days=long_window_days)
    label_end_dt = cutoff_dt + timedelta(days=label_days)

    short_start_str = short_start_dt.strftime("%Y-%m-%d %H:%M:%S")
    long_start_str = long_start_dt.strftime("%Y-%m-%d %H:%M:%S")
    cutoff_str = cutoff_dt.strftime("%Y-%m-%d %H:%M:%S")
    label_end_str = label_end_dt.strftime("%Y-%m-%d %H:%M:%S")

    # Historical windows
    hist_7d = events_df.filter(
        (col("timestamp") >= lit(short_start_str)) &
        (col("timestamp") < lit(cutoff_str))
    )

    hist_30d = events_df.filter(
        (col("timestamp") >= lit(long_start_str)) &
        (col("timestamp") < lit(cutoff_str))
    )

    # Future label window
    future_events = events_df.filter(
        (col("timestamp") >= lit(cutoff_str)) &
        (col("timestamp") < lit(label_end_str))
    )

    # Add event flags
    hist_7d = add_event_flags(hist_7d)
    hist_30d = add_event_flags(hist_30d)

    # Aggregate features
    features_7d = aggregate_features(hist_7d, "7d")
    features_30d = aggregate_features(hist_30d, "30d")

    # Join 7d and 30d features
    features = (
        features_30d
        .join(features_7d, on="user_id", how="outer")
        .withColumn("cutoff_date", lit(cutoff_date_str))
    )

    # Recency features
    features = (
        features
        .withColumn(
            "days_since_last_event_7d",
            datediff(col("cutoff_date").cast("date"), col("last_event_ts_7d").cast("date"))
        )
        .withColumn(
            "days_since_last_event_30d",
            datediff(col("cutoff_date").cast("date"), col("last_event_ts_30d").cast("date"))
        )
        .drop("last_event_ts_7d", "last_event_ts_30d")
    )

    # Fill missing values
    fill_values = {
        "views_7d": 0,
        "clicks_7d": 0,
        "carts_7d": 0,
        "purchases_7d": 0,
        "spend_7d": 0.0,
        "avg_order_value_7d": 0.0,
        "distinct_products_7d": 0,
        "active_days_7d": 0,
        "views_30d": 0,
        "clicks_30d": 0,
        "carts_30d": 0,
        "purchases_30d": 0,
        "spend_30d": 0.0,
        "avg_order_value_30d": 0.0,
        "distinct_products_30d": 0,
        "active_days_30d": 0,
        "days_since_last_event_7d": 999,
        "days_since_last_event_30d": 999,
    }

    features = features.fillna(fill_values)

    # Ratio features
    features = (
        features
        .withColumn(
            "click_to_view_ratio_7d",
            when(col("views_7d") > 0, col("clicks_7d") / col("views_7d")).otherwise(lit(0.0))
        )
        .withColumn(
            "cart_to_click_ratio_7d",
            when(col("clicks_7d") > 0, col("carts_7d") / col("clicks_7d")).otherwise(lit(0.0))
        )
        .withColumn(
            "click_to_view_ratio_30d",
            when(col("views_30d") > 0, col("clicks_30d") / col("views_30d")).otherwise(lit(0.0))
        )
        .withColumn(
            "cart_to_click_ratio_30d",
            when(col("clicks_30d") > 0, col("carts_30d") / col("clicks_30d")).otherwise(lit(0.0))
        )
    )

    # Labels: purchased in next 7 days
    labels = (
        future_events
        .filter(col("event_type") == "purchase")
        .groupBy("user_id")
        .agg(lit(1).alias("label_purchased_next_7d"))
    )

    # Join features with labels
    snapshot = (
        features
        .join(labels, on="user_id", how="left")
        .fillna({"label_purchased_next_7d": 0})
    )

    return snapshot


# --------------------------------------------------
# 7. Build all snapshots and union them together
# --------------------------------------------------
snapshots = [
    build_training_snapshot(
        events_df=events,
        cutoff_date_str=cutoff_date,
        short_window_days=short_window_days,
        long_window_days=long_window_days,
        label_days=label_days
    )
    for cutoff_date in cutoff_dates
]

if not snapshots:
    raise ValueError("No valid cutoff dates were generated. Check your data range.")

training_df = reduce(lambda df1, df2: df1.unionByName(df2), snapshots)

print("Training dataset preview:")
training_df.show(10, truncate=False)
training_df.printSchema()


# --------------------------------------------------
# 8. Choose final feature columns
# --------------------------------------------------
feature_cols = [
    "views_7d",
    "clicks_7d",
    "carts_7d",
    "purchases_7d",
    "spend_7d",
    "avg_order_value_7d",
    "distinct_products_7d",
    "active_days_7d",
    "days_since_last_event_7d",
    "click_to_view_ratio_7d",
    "cart_to_click_ratio_7d",
    "views_30d",
    "clicks_30d",
    "carts_30d",
    "purchases_30d",
    "spend_30d",
    "avg_order_value_30d",
    "distinct_products_30d",
    "active_days_30d",
    "days_since_last_event_30d",
    "click_to_view_ratio_30d",
    "cart_to_click_ratio_30d",
]


# --------------------------------------------------
# 9. Prepare Spark ML dataset
# --------------------------------------------------
assembler = VectorAssembler(
    inputCols=feature_cols,
    outputCol="features"
)

ml_df = assembler.transform(training_df).select(
    "user_id",
    "cutoff_date",
    "features",
    col("label_purchased_next_7d").alias("label")
)

print("Spark ML dataset preview:")
ml_df.show(5, truncate=False)


# --------------------------------------------------
# 10. Optional: time-based train/test split
# --------------------------------------------------
# Example split date; adjust based on your data
split_cutoff_date = cutoff_dates[int(len(cutoff_dates) * 0.8)] if len(cutoff_dates) > 1 else cutoff_dates[0]

train_df = ml_df.filter(col("cutoff_date") <= lit(split_cutoff_date))
test_df = ml_df.filter(col("cutoff_date") > lit(split_cutoff_date))

print("Train rows:", train_df.count())
print("Test rows:", test_df.count())


# --------------------------------------------------
# 11. Optional: prepare for scikit-learn
# --------------------------------------------------
sklearn_df = training_df.select(
    ["user_id", "cutoff_date", "label_purchased_next_7d"] + feature_cols
)

# Warning: only do this if the dataset is small enough to fit in memory
pdf = sklearn_df.toPandas()

X = pdf[feature_cols]
y = pdf["label_purchased_next_7d"]

print("scikit-learn feature shape:", X.shape)
print("scikit-learn label shape:", y.shape)


# --------------------------------------------------
# 12. Save outputs
# --------------------------------------------------

# Training dataset suitable for use with pandas and scikit-learn
training_df.write.mode("overwrite").parquet("output/training_dataset")
training_df.write.mode("overwrite").option("header", True).csv("output/training_dataset_csv")

# ml_dataset is intended for future use with Spark ML (contains a
# Spark vector column called "features")
ml_df.write.mode("overwrite").parquet("output/ml_dataset")
# ml_df.write.mode("overwrite").csv("output/ml_dataset")  # Not supported -- [UNSUPPORTED_DATA_TYPE_FOR_DATASOURCE] The CSV datasource doesn't support the column `features` of the type UDT("STRUCT<type: TINYINT NOT NULL, size: INT, indices: ARRAY<INT>, values: ARRAY<DOUBLE>>").

print("Done. Outputs written to:")
print(" - output/training_dataset")
print(" - output/ml_dataset")
