# Generated by ChatGPT, with additional changes/adjustments
# 2026-04-07
#
# This is an incremental step towards a more comprehensive solution
# that allows continuous model training and evaluation.
#
# NOTE: The training/test cutoff date is hardcoded below for simplicity

import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, classification_report
import joblib

df = pd.read_parquet("output/training_dataset", engine="pyarrow")

df["cutoff_date"] = pd.to_datetime(df["cutoff_date"])

feature_cols = [
    "views_7d",
    "clicks_7d",
    "carts_7d",
    "purchases_7d",
    "spend_7d",
    "avg_order_value_7d",
    "distinct_products_7d",
    "active_days_7d",
    "days_since_last_event_7d",
    "click_to_view_ratio_7d",
    "cart_to_click_ratio_7d",
    "views_30d",
    "clicks_30d",
    "carts_30d",
    "purchases_30d",
    "spend_30d",
    "avg_order_value_30d",
    "distinct_products_30d",
    "active_days_30d",
    "days_since_last_event_30d",
    "click_to_view_ratio_30d",
    "cart_to_click_ratio_30d"
]

label_col = "label_purchased_next_7d"

train_df = df[df["cutoff_date"] <= "2026-03-20"]
test_df = df[df["cutoff_date"] > "2026-03-20"]

X_train = train_df[feature_cols]
y_train = train_df[label_col]
X_test = test_df[feature_cols]
y_test = test_df[label_col]

model = Pipeline([
    ("scaler", StandardScaler()),       # Standardize feature values by subtracting the mean, and scaling to unit variance ("centering and scaling")
    ("clf", LogisticRegression(max_iter=1000))    # "clf" is a common abbreviation for "classifier"
])

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_proba = model.predict_proba(X_test)[:, 1]

print("ROC AUC:", roc_auc_score(y_test, y_proba))
print(classification_report(y_test, y_pred))

# Save the model to a file for later use (inference in production)
joblib.dump(model, "../purchase_model.joblib")


print("\n\nTesting inference with a single feature vector:")

def predict_user(model, feature_dict):
    df = pd.DataFrame([feature_dict])
    pred = model.predict(df)[0]
    proba = model.predict_proba(df)[0][1]
    
    return {
        "prediction": int(pred),
        "probability": float(proba)
    }

# Create a single example (as a dict)
sample = {
    "views_7d": 10,
    "clicks_7d": 4,
    "carts_7d": 1,
    "purchases_7d": 0,
    "spend_7d": 0.0,
    "avg_order_value_7d": 0.0,
    "distinct_products_7d": 3,
    "active_days_7d": 2,
    "days_since_last_event_7d": 1,
    "click_to_view_ratio_7d": 0.4,
    "cart_to_click_ratio_7d": 0.25,
    "views_30d": 40,
    "clicks_30d": 15,
    "carts_30d": 5,
    "purchases_30d": 1,
    "spend_30d": 50.0,
    "avg_order_value_30d": 50.0,
    "distinct_products_30d": 10,
    "active_days_30d": 12,
    "days_since_last_event_30d": 1,
    "click_to_view_ratio_30d": 0.375,
    "cart_to_click_ratio_30d": 0.33,
}

sample_result = predict_user(model, sample)
pred = sample_result["prediction"]
proba = sample_result["probability"]

print("Sample feature vector:", sample)
print("Prediction (0=no, 1=yes):", pred)
print("Probability of purchase:", proba)
