# Generated by ChatGPT, with additional changes/adjustments
# 2026-04-07
#
# This is an incremental step towards a more comprehensive solution
# that allows continuous model training and evaluation.
#
# NOTE: The training/test cutoff date is hardcoded below for simplicity

import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score, classification_report

df = pd.read_parquet("output/training_dataset", engine="pyarrow")

df["cutoff_date"] = pd.to_datetime(df["cutoff_date"])

feature_cols = [
    "views_7d",
    "clicks_7d",
    "carts_7d",
    "purchases_7d",
    "spend_7d",
    "avg_order_value_7d",
    "distinct_products_7d",
    "active_days_7d",
    "days_since_last_event_7d",
    "click_to_view_ratio_7d",
    "cart_to_click_ratio_7d",
    "views_30d",
    "clicks_30d",
    "carts_30d",
    "purchases_30d",
    "spend_30d",
    "avg_order_value_30d",
    "distinct_products_30d",
    "active_days_30d",
    "days_since_last_event_30d",
    "click_to_view_ratio_30d",
    "cart_to_click_ratio_30d"
]

label_col = "label_purchased_next_7d"

train_df = df[df["cutoff_date"] <= "2026-03-20"]
test_df = df[df["cutoff_date"] > "2026-03-20"]

X_train = train_df[feature_cols]
y_train = train_df[label_col]
X_test = test_df[feature_cols]
y_test = test_df[label_col]

model = Pipeline([
    ("scaler", StandardScaler()),       # Standardize feature values by subtracting the mean, and scaling to unit variance ("centering and scaling")
    ("clf", LogisticRegression(max_iter=1000))    # "clf" is a common abbreviation for "classifier"
])

model.fit(X_train, y_train)

y_pred = model.predict(X_test)
y_proba = model.predict_proba(X_test)[:, 1]

print("ROC AUC:", roc_auc_score(y_test, y_proba))
print(classification_report(y_test, y_pred))